// Code generated by mockery v1.0.0
package consumer

import context "golang.org/x/net/context"
import mock "github.com/stretchr/testify/mock"

// MockConsumerServer is an autogenerated mock type for the ConsumerServer type
type MockConsumerServer struct {
	mock.Mock
}

// CurrentConsumerState provides a mock function with given fields: _a0, _a1
func (_m *MockConsumerServer) CurrentConsumerState(_a0 context.Context, _a1 *Empty) (*ConsumerState, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *ConsumerState
	if rf, ok := ret.Get(0).(func(context.Context, *Empty) *ConsumerState); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ConsumerState)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *Empty) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
