version: 2
jobs:
  build:
    docker:
      - image: gazette/ci-builder:20200421
    environment:
      # Instruct the go tool to place the module cache under the working
      # directory (~/project)
      GOPATH: /root/project/.build/go-path
      # RocksDB version to build. Keep in sync with mk/config.mk
      # Also be sure to update the save_cache step below.
      ROCKSDB_VERSION: 6.22.1
      # `nproc` on CircleCI docker runners returns the number of host cores,
      # not provisioned cores (eg, 36 cores when only 2 are available).
      NPROC: 2
      # Same issue with GOMAXPROCS.
      GOMAXPROCS: 2
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          # We can't use a variable here :( Must be hard-coded.
          # https://discuss.circleci.com/t/cannot-use-circle-yml-environment-variables-in-cache-keys/10994
          key: rocksdb-v1-v6.22.1
      - run:
          name: Build RocksDB
          command: make $(pwd)/.build/rocksdb-v${ROCKSDB_VERSION}/librocksdb.so
      - save_cache:
          name: Cache RocksDB
          key: rocksdb-v1-v6.22.1
          paths:
            # We *also* can't use a variable here (seriously?!).
            # https://discuss.circleci.com/t/can-i-use-variables-in-cache-paths/11393
            - .build/rocksdb-v6.22.1/
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
            - go-mod-v1-
      - run:
          name: Go Install
          command: make go-install
      - run:
          name: Go Test
          command: make go-test-ci
      - save_cache:
          name: Cache Go Modules
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - .build/go-path/pkg
  release:
    docker:
      - image: gazette/ci-builder:20200421
    steps:
      - run:
          name: Publish Gazette
          command: echo "release tag  ${CIRCLE_TAG}"

workflows:
  version: 2
  build:
    jobs:
      - build
  release:
    jobs:
      - release:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
