version: 2.1
commands:
  prepare_build_env:
    description: Prepare build environment
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install bash
          command: apk add --no-cache --no-progress bash
jobs:
  build_v1:
    docker:
      - image: docker:stable
    steps:
      - prepare_build_env
      - run:
          name: Install bash
          command: apk add --no-cache bash

      - run:
          name: Build and test V1 Gazette
          command: docker build . --file build/Dockerfile.gazette-build --tag gazette-build
      - run:
          name: Build the V1 binary image
          command: docker build . --file build/cmd/Dockerfile.gazette
      - run:
          name: Build V1 stream-sum example
          command: docker build . --file build/examples/Dockerfile.stream-sum

  build_v2:
    docker:
      - image: docker:stable
    steps:
      - prepare_build_env
      - run:
          name: Build and test V2 Gazette
          command: ./v2/build/all .
  publish_images:
    docker:
      - image: docker:stable
    steps:
      - prepare_build_env
      - run:
          name: Build and publish V2 Gazette
          command: ./v2/build/release . "${CIRCLE_TAG}"
workflows:
  version: 2
  build_all:
    jobs:
      - build_v1
      - build_v2
  release:
    jobs:
      - publish_images:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
