apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "consumer.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "consumer.name" . }}
    helm.sh/chart: {{ include "consumer.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "consumer.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "consumer.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ required "Must provide image.repository" .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /debug/ready
              port: http
          readinessProbe:
            httpGet:
              path: /debug/ready
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
          command:
            # Run within a shell to allow for interpretation of values.
            - "/bin/sh"
            - "-ec"
            - |
              exec {{ required "Must provide image.binary" .Values.image.binary }} serve \
                --broker.address={{ .Values.gazette.endpoint }} \
                --consumer.port=8080 \
                --consumer.zone=$(/root/.config/zonemap/node-zone.sh $NODE_NAME) \
                --etcd.address={{ .Values.etcd.endpoint }} \
                --etcd.prefix={{ .Values.etcd.partialPrefix }}/{{ required "Must provide nameOverride" .Values.nameOverride }} \
{{ .Values.extraArgs | indent 16 }}
          env:
            - name: CONSUMER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: CONSUMER_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            {{- if .Values.extraEnv }}
{{ toYaml .Values.extraEnv | indent 12 }}
            {{- end}}

          volumeMounts:
            - name: tmpdir
              mountPath: /tmp
            - name: zonemap
              readOnly: true
              mountPath: /root/.config/zonemap
            - name: config
              readOnly: true
              mountPath: /root/.config/gazette

            {{- if .Values.extraVolumeMounts }}
{{ toYaml .Values.extraVolumeMounts | indent 12 }}
            {{- end}}

      volumes:
        # tmpdir is used for all ephemeral and temporary files, such as journal spools.
        # Defaults to an emptyDir, but operators may want to supply a fast local disk.
        - name: tmpdir
          {{- if .Values.tmpdir }}
{{ toYaml .Values.tmpdir | indent 10 }}
          {{- else }}
          emptyDir: {}
          {{- end }}

        # The deployment must be able to determine the failure zone of the Node
        # of each Pod. Kubernetes makes this difficult to determine, as the
        # downward API deliberately does not expose Node labels (and specifically,
        # the "failure-domain.beta.kubernetes.io/zone" label). This chart pushes
        # this mapping concern into a "gazette-zonemap" ConfigMap, which must
        # provide a "node-zone.sh" script capable of accepting a Node name and
        # returning its failure zone. The cluster operator must generate and apply
        # a suitable ConfigMap. See:
        #  * v2/charts/generate-zonemap-gke.sh
        #  * v2/charts/generate-zonemap-testing.sh
        - name: zonemap
          configMap:
            name: gazette-zonemap
            items:
              - key: node-zone.sh
                path: node-zone.sh
                mode: 511 # Equivalent to 0777.
        - name: config
          configMap:
            name: {{ include "consumer.fullname" . }}

        {{- if .Values.extraVolumes }}
{{ toYaml .Values.extraVolumes | indent 8 }}
        {{- end}}

      # Give pods plenty of time to shutdown gracefully after SIGTERM.
      terminationGracePeriodSeconds: 21600
      automountServiceAccountToken: false

    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
