# Default values for word-count.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 3
image:
  repository: stream-sum
  tag: latest
  pullPolicy: IfNotPresent
etcd:
  endpoint: "http://etcd-cluster-client:2379"
gazette:
  endpoint: "http://gazette-gazette:8081"
chunker:
  numJobs: 10
  numStreams: 1000
  chunksPerStream: 100
