apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "word-count.fullname" . }}
data:
  config.yaml: |
    # YAML Configuration of the `word-count` example.

    service:
      # Absolute path in Etcd of the service consensus.Allocator.
      allocatorRoot: # Provided by environment.
      # Unique key of this consumer instance. By convention, this is a bound "host:port" address.
      localRouteKey: # Provided by environment.
      # Path of consumer plugin to load & run.
      plugin: # Provided by environment.
      # Path prefix for the consumer's recovery-log Journals.
      recoveryLogRoot: examples/word-count/recovery-logs
      # Number of warm-standby replicas to allocate for each Consumer shard.
      shardStandbys: 1
      # Local directory for ephemeral serving files.
      workdir: /var/tmp

    # Service addresses to use.
    etcd:
      endpoint: "{{ .Values.etcd.endpoint }}"
    gazette:
      endpoint: "{{ .Values.gazette.endpoint }}"
