// Code generated by mockery v1.0.0
package journal

import mock "github.com/stretchr/testify/mock"
import url "net/url"

// MockHeader is an autogenerated mock type for the Header type
type MockHeader struct {
	mock.Mock
}

// Head provides a mock function with given fields: args
func (_m *MockHeader) Head(args ReadArgs) (ReadResult, *url.URL) {
	ret := _m.Called(args)

	var r0 ReadResult
	if rf, ok := ret.Get(0).(func(ReadArgs) ReadResult); ok {
		r0 = rf(args)
	} else {
		r0 = ret.Get(0).(ReadResult)
	}

	var r1 *url.URL
	if rf, ok := ret.Get(1).(func(ReadArgs) *url.URL); ok {
		r1 = rf(args)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*url.URL)
		}
	}

	return r0, r1
}
