# Default values for word-count.
# This is a YAML-formatted file.

counter:
  replicaCount: 3

  # Size of NGrams produced by the consumer.
  NGramSize: 2

  image:
    repository: liveramp/gazette-examples
    binary: /go/bin/counter

  extraArgs:
    --wordcount.N: "{{ .Values.NGramSize }}"
